chore: update workflow

diff --git a/.github/workflows/version-increment.yml b/.github/workflows/version-increment.yml
--- a/.github/workflows/version-increment.yml
+++ b/.github/workflows/version-increment.yml
@@ -16,9 +16,9 @@ jobs:
           !contains(github.event.pull_request.labels.*.name, 'release:patch') &&
           !contains(github.event.pull_request.labels.*.name, 'release:minor') &&
           !contains(github.event.pull_request.labels.*.name, 'release:major')
-        run: |
-          echo "::error::リリースラベルを付与してください。labels: release:patch, release:minor, release:major"
-          exit 1
+        # run: |
+        #   echo "::error::リリースラベルを付与してください。labels: release:patch, release:minor, release:major"
+        #   exit 1
   version_diff:
     if: |
       contains(github.event.pull_request.labels.*.name, 'release:patch') ||
