chore: update gh version increment

diff --git a/.github/workflows/version-increment.yml b/.github/workflows/version-increment.yml
--- a/.github/workflows/version-increment.yml
+++ b/.github/workflows/version-increment.yml
@@ -5,30 +5,40 @@ on:
      - main
    types:
      - labeled
+     - unlabeled
 jobs:
-  version_diff_app:
+  check_release_label:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check release label
+        if: |
+          !contains(github.event.pull_request.labels.*.name, 'release:patch') &&
+          !contains(github.event.pull_request.labels.*.name, 'release:minor') &&
+          !contains(github.event.pull_request.labels.*.name, 'release:major')
+        run: |
+          echo "::error::リリースラベルを付与してください。labels: release:patch, release:minor, release:major"
+          exit 1
+  version_diff:
     if: |
       contains(github.event.pull_request.labels.*.name, 'release:patch') ||
       contains(github.event.pull_request.labels.*.name, 'release:minor') ||
       contains(github.event.pull_request.labels.*.name, 'release:major')
     runs-on: ubuntu-latest
     outputs:
-      changed: ${{ steps.get_diff.outputs.changed }}
+      chagned: ${{ steps.get_diff.outputs.changed }}
     steps:
       - uses: actions/checkout@v3
 
-      - name: Get branch to merge
+      - name: Get branch to marge
         run: git fetch origin ${{ github.base_ref }} --depth=1
 
       - name: Keep version changes
         id: get_diff
-        working-directory: ./
-        run: echo "changed=$(git diff origin/${{ github.base_ref }} HEAD --relative package.json | grep "^+.\+version" | wc -l)" >> $GITHUB_OUTPUT
+        run: echo "changed=$(git diff origin/${{ github.base_ref }} HEAD --relative "./package.json" | grep "^+.\+version" | wc -l)" >> $GITHUB_OUTPUT
   update_version:
     runs-on: ubuntu-latest
-    needs: [version_diff_app]
-    if: |
-      needs.version_diff_app.outputs.changed == '0'
+    needs: [version_diff]
+    if: needs.version_diff.outputs.chagned == '0'
     steps:
       - uses: actions/checkout@v3
         with:
@@ -36,7 +46,7 @@ jobs:
 
       - uses: actions/setup-node@v3
         with:
-          node-version: 18.11.9
+          node-version: 16
 
       - uses: pnpm/action-setup@v2
         with:
@@ -46,29 +56,25 @@ jobs:
         if: steps.diff.outputs.changed == '0'
         run: |
           git config --global user.name 'user-name-cong'
-          git config --global user.email 'user-email-cong@midota.com'
+          git config --global user.email 'user-email-cong@gmail.com'
           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Update version App(patch)
+      - name: Update version(patch)
         if: contains(github.event.pull_request.labels.*.name, 'release:patch')
-        working-directory: ./
         run: pnpm version patch --no-git-tag-version
 
-      - name: Update version App(minor)
+      - name: Update version(minor)
         if: contains(github.event.pull_request.labels.*.name, 'release:minor')
-        working-directory: ./
         run: pnpm version minor --no-git-tag-version
 
-      - name: Update version App(major)
+      - name: Update version(major)
         if: contains(github.event.pull_request.labels.*.name, 'release:major')
-        working-directory: ./
         run: pnpm version major --no-git-tag-version
 
       - name: Commit and push to PR
-        working-directory: ./
         run: |
           git add .
-          git commit -m "Project v$(grep version './package.json' | awk -F \" '{print $4}')"
+          git commit -m "v$(grep version package.json | awk -F \" '{print $4}')"
           git push origin HEAD
